Data_Subset <- subset(household_power_consumption,V1 == "01/02/2007" | V1 == "02/02/2007")
globalActivePower <- as.numeric(Data_Subset$V3)
datetime <- strptime(paste(Data_Subset$V1, Data_Subset$V2, sep=" "), "%d/%m/%Y %H:%M:%S") 
subMetering1 <- as.numeric(Data_Subset$V7)
subMetering2 <- as.numeric(Data_Subset$V8)
subMetering3 <- as.numeric(Data_Subset$V9)
png("plot3.png", width=480, height=480)
plot(datetime, subMetering1, type="l", ylab="Energy Submetering", xlab="")
lines(datetime, subMetering2, type="l", col="red")
lines(datetime, subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()
